### ISSUE TITLE
Error generating TensorRT engines

### ISSUE THREAD

**Issue by IamShubhamGupto** [NVIDIA-AI-IOT/nanoowl#5]
Hello!

I am using a docker image running JP5.1 to test nanoowl on the jetson Orin. I followed the instructions for generating the engine file but I am getting errors. I believe it could also be a TensorRT problem / memory issue. I tried downloading the latest torch2trt build, gave trtexec rwx permissions and set the workspace size to `2048` according to https://github.com/NVIDIA/TensorRT/issues/1581#issuecomment-1609136974

the logs:

```
root@ultraviolet:/home/ultraviolet/nanoowl# python3 -m nanoowl.build_image_encoder_engine     data/owl_image_encoder_patch32.engine
/usr/local/lib/python3.8/dist-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/pytorch/pytorch/aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/usr/local/lib/python3.8/dist-packages/transformers/models/owlvit/modeling_owlvit.py:401: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if attn_weights.size() != (bsz * self.num_heads, tgt_len, src_len):
/usr/local/lib/python3.8/dist-packages/transformers/models/owlvit/modeling_owlvit.py:444: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if attn_output.size() != (bsz * self.num_heads, tgt_len, self.head_dim):
============ Diagnostic Run torch.onnx.export version 2.0.0+nv23.05 ============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

&&&& RUNNING TensorRT.trtexec [TensorRT v8502] # /usr/src/tensorrt/bin/trtexec --onnx=/tmp/tmpjw0kswm6/image_encoder.onnx --saveEngine=data/owl_image_encoder_patch32.engine --fp16 --shapes=image:1x3x768x768 --workspace=2048
[10/19/2023-14:48:00] [I] === Model Options ===
[10/19/2023-14:48:00] [I] Format: ONNX
[10/19/2023-14:48:00] [I] Model: /tmp/tmpjw0kswm6/image_encoder.onnx
[10/19/2023-14:48:00] [I] Output:
[10/19/2023-14:48:00] [I] === Build Options ===
[10/19/2023-14:48:00] [I] Max batch: explicit batch
[10/19/2023-14:48:00] [I] Memory Pools: workspace: default, dlaSRAM: default, dlaLocalDRAM: default, dlaGlobalDRAM: default
[10/19/2023-14:48:00] [I] minTiming: 1
[10/19/2023-14:48:00] [I] avgTiming: 8
[10/19/2023-14:48:00] [I] Precision: FP32+FP16
[10/19/2023-14:48:00] [I] LayerPrecisions: 
[10/19/2023-14:48:00] [I] Calibration: 
[10/19/2023-14:48:00] [I] Refit: Disabled
[10/19/2023-14:48:00] [I] Sparsity: Disabled
[10/19/2023-14:48:00] [I] Safe mode: Disabled
[10/19/2023-14:48:00] [I] DirectIO mode: Disabled
[10/19/2023-14:48:00] [I] Restricted mode: Disabled
[10/19/2023-14:48:00] [I] Build only: Disabled
[10/19/2023-14:48:00] [I] Save engine: data/owl_image_encoder_patch32.engine
[10/19/2023-14:48:00] [I] Load engine: 
[10/19/2023-14:48:00] [I] Profiling verbosity: 0
[10/19/2023-14:48:00] [I] Tactic sources: Using default tactic sources
[10/19/2023-14:48:00] [I] timingCacheMode: local
[10/19/2023-14:48:00] [I] timingCacheFile: 
[10/19/2023-14:48:00] [I] Heuristic: Disabled
[10/19/2023-14:48:00] [I] Preview Features: Use default preview flags.
[10/19/2023-14:48:00] [I] Input(s)s format: fp32:CHW
[10/19/2023-14:48:00] [I] Output(s)s format: fp32:CHW
[10/19/2023-14:48:00] [I] Input build shape: image=1x3x768x768+1x3x768x768+1x3x768x768
[10/19/2023-14:48:00] [I] Input calibration shapes: model
[10/19/2023-14:48:00] [I] === System Options ===
[10/19/2023-14:48:00] [I] Device: 0
[10/19/2023-14:48:00] [I] DLACore: 
[10/19/2023-14:48:00] [I] Plugins:
[10/19/2023-14:48:00] [I] === Inference Options ===
[10/19/2023-14:48:00] [I] Batch: Explicit
[10/19/2023-14:48:00] [I] Input inference shape: image=1x3x768x768
[10/19/2023-14:48:00] [I] Iterations: 10
[10/19/2023-14:48:00] [I] Duration: 3s (+ 200ms warm up)
[10/19/2023-14:48:00] [I] Sleep time: 0ms
[10/19/2023-14:48:00] [I] Idle time: 0ms
[10/19/2023-14:48:00] [I] Streams: 1
[10/19/2023-14:48:00] [I] ExposeDMA: Disabled
[10/19/2023-14:48:00] [I] Data transfers: Enabled
[10/19/2023-14:48:00] [I] Spin-wait: Disabled
[10/19/2023-14:48:00] [I] Multithreading: Disabled
[10/19/2023-14:48:00] [I] CUDA Graph: Disabled
[10/19/2023-14:48:00] [I] Separate profiling: Disabled
[10/19/2023-14:48:00] [I] Time Deserialize: Disabled
[10/19/2023-14:48:00] [I] Time Refit: Disabled
[10/19/2023-14:48:00] [I] NVTX verbosity: 0
[10/19/2023-14:48:00] [I] Persistent Cache Ratio: 0
[10/19/2023-14:48:00] [I] Inputs:
[10/19/2023-14:48:00] [I] === Reporting Options ===
[10/19/2023-14:48:00] [I] Verbose: Disabled
[10/19/2023-14:48:00] [I] Averages: 10 inferences
[10/19/2023-14:48:00] [I] Percentiles: 90,95,99
[10/19/2023-14:48:00] [I] Dump refittable layers:Disabled
[10/19/2023-14:48:00] [I] Dump output: Disabled
[10/19/2023-14:48:00] [I] Profile: Disabled
[10/19/2023-14:48:00] [I] Export timing to JSON file: 
[10/19/2023-14:48:00] [I] Export output to JSON file: 
[10/19/2023-14:48:00] [I] Export profile to JSON file: 
[10/19/2023-14:48:00] [I] 
[10/19/2023-14:48:00] [I] === Device Information ===
[10/19/2023-14:48:00] [I] Selected Device: Orin
[10/19/2023-14:48:00] [I] Compute Capability: 8.7
[10/19/2023-14:48:00] [I] SMs: 8
[10/19/2023-14:48:00] [I] Compute Clock Rate: 1.3 GHz
[10/19/2023-14:48:00] [I] Device Global Memory: 30587 MiB
[10/19/2023-14:48:00] [I] Shared Memory per SM: 164 KiB
[10/19/2023-14:48:00] [I] Memory Bus Width: 128 bits (ECC disabled)
[10/19/2023-14:48:00] [I] Memory Clock Rate: 0.612 GHz
[10/19/2023-14:48:00] [I] 
[10/19/2023-14:48:00] [I] TensorRT version: 8.5.2
[10/19/2023-14:48:00] [I] [TRT] [MemUsageChange] Init CUDA: CPU +220, GPU +0, now: CPU 249, GPU 11612 (MiB)
[10/19/2023-14:48:03] [I] [TRT] [MemUsageChange] Init builder kernel library: CPU +302, GPU +285, now: CPU 574, GPU 11913 (MiB)
[10/19/2023-14:48:03] [I] Start parsing network model
[10/19/2023-14:48:03] [I] [TRT] ----------------------------------------------------------------
[10/19/2023-14:48:03] [I] [TRT] Input filename:   /tmp/tmpjw0kswm6/image_encoder.onnx
[10/19/2023-14:48:03] [I] [TRT] ONNX IR version:  0.0.8
[10/19/2023-14:48:03] [I] [TRT] Opset version:    16
[10/19/2023-14:48:03] [I] [TRT] Producer name:    pytorch
[10/19/2023-14:48:03] [I] [TRT] Producer version: 2.0.0
[10/19/2023-14:48:03] [I] [TRT] Domain:           
[10/19/2023-14:48:03] [I] [TRT] Model version:    0
[10/19/2023-14:48:03] [I] [TRT] Doc string:       
[10/19/2023-14:48:03] [I] [TRT] ----------------------------------------------------------------
[10/19/2023-14:48:03] [W] [TRT] onnx2trt_utils.cpp:375: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[10/19/2023-14:48:07] [W] [TRT] onnx2trt_utils.cpp:403: One or more weights outside the range of INT32 was clamped
[10/19/2023-14:48:08] [I] Finish parsing network model
[10/19/2023-14:48:09] [I] [TRT] ---------- Layers Running on DLA ----------
[10/19/2023-14:48:09] [I] [TRT] ---------- Layers Running on GPU ----------
[10/19/2023-14:48:09] [I] [TRT] [GpuLayer] COPY: /vision_model/Cast
[10/19/2023-14:48:09] [I] [TRT] [GpuLayer] CONVOLUTION: /vision_model/embeddings/patch_embedding/Conv
[10/19/2023-14:48:09] [I] [TRT] [GpuLayer] MYELIN: {ForeignNode[parent.model.owlvit.vision_model.embeddings.position_embedding.weight.../Concat]}
[10/19/2023-14:48:11] [I] [TRT] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +534, GPU +438, now: CPU 1457, GPU 12789 (MiB)
[10/19/2023-14:48:11] [I] [TRT] [MemUsageChange] Init cuDNN: CPU +83, GPU +127, now: CPU 1540, GPU 12916 (MiB)
[10/19/2023-14:48:11] [I] [TRT] Local timing cache in use. Profiling results in this builder pass will not be stored.
[10/19/2023-14:49:21] [I] [TRT] Total Activation Memory: 32084996096
[10/19/2023-14:49:21] [I] [TRT] Detected 1 inputs and 5 output network tensors.
[10/19/2023-14:49:21] [I] [TRT] Total Host Persistent Memory: 2656
[10/19/2023-14:49:21] [I] [TRT] Total Device Persistent Memory: 0
[10/19/2023-14:49:21] [I] [TRT] Total Scratch Memory: 28402688
[10/19/2023-14:49:21] [I] [TRT] [MemUsageStats] Peak memory usage of TRT CPU/GPU memory allocators: CPU 182 MiB, GPU 570 MiB
[10/19/2023-14:49:21] [I] [TRT] [BlockAssignment] Started assigning block shifts. This will take 9 steps to complete.
[10/19/2023-14:49:21] [I] [TRT] [BlockAssignment] Algorithm ShiftNTopDown took 0.264098ms to assign 7 blocks to 9 nodes requiring 30769664 bytes.
[10/19/2023-14:49:21] [I] [TRT] Total Activation Memory: 30769664
[10/19/2023-14:49:21] [W] [TRT] TensorRT encountered issues when converting weights between types and that could affect accuracy.
[10/19/2023-14:49:21] [W] [TRT] If this is not the desired behavior, please modify the weights or retrain with regularization to adjust the magnitude of the weights.
[10/19/2023-14:49:21] [W] [TRT] Check verbose logs for the list of affected weights.
[10/19/2023-14:49:21] [W] [TRT] - 163 weights are affected by this issue: Detected subnormal FP16 values.
[10/19/2023-14:49:21] [W] [TRT] - 66 weights are affected by this issue: Detected values less than smallest positive FP16 subnormal value and converted them to the FP16 minimum subnormalized value.
[10/19/2023-14:49:21] [I] [TRT] [MemUsageChange] TensorRT-managed allocation in building engine: CPU +170, GPU +256, now: CPU 170, GPU 256 (MiB)
[10/19/2023-14:49:21] [E] Saving engine to file failed.
[10/19/2023-14:49:21] [E] Engine set up failed
&&&& FAILED TensorRT.trtexec [TensorRT v8502] # /usr/src/tensorrt/bin/trtexec --onnx=/tmp/tmpjw0kswm6/image_encoder.onnx --saveEngine=data/owl_image_encoder_patch32.engine --fp16 --shapes=image:1x3x768x768 --workspace=2048
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ultraviolet/nanoowl/nanoowl/build_image_encoder_engine.py", line 34, in <module>
    predictor.build_image_encoder_engine(
  File "/home/ultraviolet/nanoowl/nanoowl/owl_predictor.py", line 444, in build_image_encoder_engine
    return self.load_image_encoder_engine(engine_path, max_batch_size)
  File "/home/ultraviolet/nanoowl/nanoowl/owl_predictor.py", line 375, in load_image_encoder_engine
    with open(engine_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/owl_image_encoder_patch32.engine'
root@ultraviolet:/home/ultraviolet/nanoowl# 

```

any feedback or help is appreciated

**Comment by IamShubhamGupto** [comment]
@jaybdub Hey just bumping up this issue. Please do look into it when possible!

Thank you

**Comment by elfar** [comment]
I was not using docker but got the same error on first run as "data" directory does not exist in the repository. Have you tried either creating that directory or remove "data/" from your save path, worked for me

**Comment by jaybdub** [comment]
Hi @IamShubhamGupto ,

Thanks for reaching out.

This seems to me like the data directory might be missing also.

Let me know if @elfar 's suggestion works for you.

John

**Comment by IamShubhamGupto** [comment]
Hey @elfar 

Thanks for pointing that out, I never would have noticed it.

Im closing this issue as it works on the Jetson Orin
